version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      # Replace <host_address> with your local IP or "localhost" for testing
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://<host_address>:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"

  mysql:
    image: mysql:8.3.0
    container_name: mysql-8.3.0
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_ROOT_USER: root
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql

  user-service:
    image: nogi2k2/expense-tracker-services:user-service
    container_name: user-service
    ports:
      - '9810:9810'
    depends_on:
      - kafka
      - mysql
      - auth-service

  auth-service:
    image: nogi2k2/expense-tracker-services:auth-service
    container_name: auth-service
    ports:
      - '9898:9898'
    depends_on:
      - kafka
      - mysql

  expense-service:
    image: nogi2k2/expense-tracker-services:expense-service
    container_name: expense-service
    ports:
      - '9820:9820'
    depends_on:
      - kafka
      - mysql

  ds-service:
    image: nogi2k2/expense-tracker-services:ds-service
    container_name: ds-service
    ports:
      - '8010:8010'
    depends_on:
      - kafka
      - mysql
      - expense-service
      - user-service

volumes:
  mysql-db:
    driver: local
